### ISSUE TITLE
Daemon issues

### ISSUE THREAD

**Issue by luaus** [linescoin/lines#2]
Repeated print out of "Tx verification failed" after sync has finished.  Running on ubuntu 16.04 LTS /lines v3.2.0.24/ port 15010.

**Comment by robotech-32-71** [comment]
Make sure you are using the latest version.

"Tx verification failed" message means that your daemon can not add transaction to the transaction pool. Usually this happens when something is wrong in the transaction itself or daemon's version is not the current. 

You can hide this message with "set_log 1" command.

**Comment by linescoin** [comment]
Yes, v3.2.0.24 is the latest version. What kind of pool software do you use?

**Comment by luaus** [comment]
solved, although all the warnings of invalid tx and wrong block versions in the daemon are misleading...solved the orphan block issue by `apiInterfaces.rpcDaemon('getblockheaderbyheight', {height: block.height + 1}, function(error, result){` in lib/blockUnlocker.js on the pool software side.
